require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SketchesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Sketch. As you add validations to Sketch, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SketchesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all sketches as @sketches" do
      sketch = Sketch.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:sketches)).to eq([sketch])
    end
  end

  describe "GET #show" do
    it "assigns the requested sketch as @sketch" do
      sketch = Sketch.create! valid_attributes
      get :show, {:id => sketch.to_param}, valid_session
      expect(assigns(:sketch)).to eq(sketch)
    end
  end

  describe "GET #new" do
    it "assigns a new sketch as @sketch" do
      get :new, {}, valid_session
      expect(assigns(:sketch)).to be_a_new(Sketch)
    end
  end

  describe "GET #edit" do
    it "assigns the requested sketch as @sketch" do
      sketch = Sketch.create! valid_attributes
      get :edit, {:id => sketch.to_param}, valid_session
      expect(assigns(:sketch)).to eq(sketch)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Sketch" do
        expect {
          post :create, {:sketch => valid_attributes}, valid_session
        }.to change(Sketch, :count).by(1)
      end

      it "assigns a newly created sketch as @sketch" do
        post :create, {:sketch => valid_attributes}, valid_session
        expect(assigns(:sketch)).to be_a(Sketch)
        expect(assigns(:sketch)).to be_persisted
      end

      it "redirects to the created sketch" do
        post :create, {:sketch => valid_attributes}, valid_session
        expect(response).to redirect_to(Sketch.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved sketch as @sketch" do
        post :create, {:sketch => invalid_attributes}, valid_session
        expect(assigns(:sketch)).to be_a_new(Sketch)
      end

      it "re-renders the 'new' template" do
        post :create, {:sketch => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested sketch" do
        sketch = Sketch.create! valid_attributes
        put :update, {:id => sketch.to_param, :sketch => new_attributes}, valid_session
        sketch.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested sketch as @sketch" do
        sketch = Sketch.create! valid_attributes
        put :update, {:id => sketch.to_param, :sketch => valid_attributes}, valid_session
        expect(assigns(:sketch)).to eq(sketch)
      end

      it "redirects to the sketch" do
        sketch = Sketch.create! valid_attributes
        put :update, {:id => sketch.to_param, :sketch => valid_attributes}, valid_session
        expect(response).to redirect_to(sketch)
      end
    end

    context "with invalid params" do
      it "assigns the sketch as @sketch" do
        sketch = Sketch.create! valid_attributes
        put :update, {:id => sketch.to_param, :sketch => invalid_attributes}, valid_session
        expect(assigns(:sketch)).to eq(sketch)
      end

      it "re-renders the 'edit' template" do
        sketch = Sketch.create! valid_attributes
        put :update, {:id => sketch.to_param, :sketch => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested sketch" do
      sketch = Sketch.create! valid_attributes
      expect {
        delete :destroy, {:id => sketch.to_param}, valid_session
      }.to change(Sketch, :count).by(-1)
    end

    it "redirects to the sketches list" do
      sketch = Sketch.create! valid_attributes
      delete :destroy, {:id => sketch.to_param}, valid_session
      expect(response).to redirect_to(sketches_url)
    end
  end

end
